<script lang="ts">
	import * as Form from '$lib/components/ui/form';
	import { Button } from '$lib/components/ui/button';
	import { FileSelection, Checkbox } from '$lib/components/ui/input';
	import { app } from '$core/app/context';
	import { settings } from '$core/config/settings.svelte';
	import { H } from '$lib/components/ui/h';
	import dayjs from '$lib/dayjs';
	import ImportIcon from 'phosphor-svelte/lib/DownloadSimpleIcon';
	import ExportIcon from 'phosphor-svelte/lib/ExportIcon';
	import ArchiveIcon from 'phosphor-svelte/lib/ArchiveIcon';

	let backupDir = $state('');
	let lastBackupAt = $state<Date | null>(settings.backup.lastBackupAt);
	let isBackingUp = $state(false);

	$effect(() => {
		settings.paths.backupDir().then((dir) => {
			backupDir = dir;
		});
	});

	const backupNow = async () => {
		isBackingUp = true;

		try {
			await settings.backup.backupNow('manual');
			lastBackupAt = settings.backup.lastBackupAt;

			if (settings.backup.lastError) {
				app.toast.error(`Backup failed: ${settings.backup.lastError}`);
			} else {
				app.toast.success('Backup created.');
			}
		} finally {
			isBackingUp = false;
		}
	};
</script>

<H level="1">Settings</H>
<Form.Root>
	<Form.Group>
		<Form.Label>Launch at startup</Form.Label>
		<Form.Description>
			Enable or disable launching the application automatically when your system starts.
		</Form.Description>
		<Checkbox label="Launch at startup" bind:checked={app.settings.autostart} />
	</Form.Group>
	<Form.Group>
		<Form.Label>Company of Heroes warnings.log</Form.Label>
		<Form.Description>
			Select the warnings.log file generated by Company of Heroes. The app needs this file to
			detect your games.
		</Form.Description>
		<FileSelection
			name="pathToConfig"
			bind:value={app.settings.companyOfHeroesConfigPath}
			filters={[{ name: 'warnings.log', extensions: ['log'] }]}
		/>
	</Form.Group>
	<Form.Group>
		<Form.Label>Company of Heroes installation folder</Form.Label>
		<Form.Description>
			Select the root installation folder of Company of Heroes (contains RelicCOH.exe).
		</Form.Description>
		<FileSelection
			name="pathToInstallation"
			directory
			bind:value={app.settings.companyOfHeroesInstallationPath}
		/>
	</Form.Group>
	<H level="4">Import / Export</H>
	<Form.Group>
		<Form.Label>Import configuration</Form.Label>
		<Form.Description>
			Import a configuration JSON file to restore your settings. The file is validated first and
			applied immediately; nothing changes when the file is invalid.
		</Form.Description>
		<Button variant="secondary" type="button" class="w-fit" onclick={() => app.importSettings()}>
			<ImportIcon />
			Import
		</Button>
	</Form.Group>
	<Form.Group>
		<Form.Label>Export configuration</Form.Label>
		<Form.Description>
			Export your full configuration (including your account and feature settings) to a JSON file.
		</Form.Description>
		<Button variant="secondary" type="button" class="w-fit" onclick={() => app.exportSettings()}>
			<ExportIcon />
			Export
		</Button>
	</Form.Group>
	<H level="4">Backups</H>
	<Form.Group>
		<Form.Label>Automatic backups</Form.Label>
		<Form.Description>
			Your settings and account are automatically backed up to
			<code class="text-secondary-300">{backupDir}</code>, outside the app's data folder. They
			survive updates, even when you choose to remove all app data.
			{#if lastBackupAt}
				<br />Last backup: {dayjs(lastBackupAt).format('DD MMM YYYY, HH:mm:ss')}
			{/if}
		</Form.Description>
		<Button
			variant="secondary"
			type="button"
			class="w-fit"
			onclick={backupNow}
			loading={isBackingUp}
		>
			<ArchiveIcon />
			Backup now
		</Button>
	</Form.Group>
</Form.Root>
