<script lang="ts">
	import * as Form from '$lib/components/ui/form';
	import { Button } from '$lib/components/ui/button';
	import { FileSelection, Checkbox, SelectLocale } from '$lib/components/ui/input';
	import { app } from '$core/app/context';
	import { settings } from '$core/config/settings.svelte';
	import { antiCheat } from '$core/app/features/anti-cheat';
	import { H } from '$lib/components/ui/h';
	import dayjs from '$lib/dayjs';
	import ImportIcon from 'phosphor-svelte/lib/DownloadSimpleIcon';
	import ExportIcon from 'phosphor-svelte/lib/ExportIcon';
	import ArchiveIcon from 'phosphor-svelte/lib/ArchiveIcon';
	import { useI18n } from '$lib/i18n';

	const { t } = useI18n();

	let backupDir = $state('');
	let lastBackupAt = $state<Date | null>(settings.backup.lastBackupAt);
	let isBackingUp = $state(false);

	$effect(() => {
		settings.paths.backupDir().then((dir) => {
			backupDir = dir;
		});
	});

	const backupNow = async () => {
		isBackingUp = true;

		try {
			await settings.backup.backupNow('manual');
			lastBackupAt = settings.backup.lastBackupAt;

			if (settings.backup.lastError) {
				app.toast.error(t('Backup failed: {message}', { message: settings.backup.lastError }));
			} else {
				app.toast.success(t('Backup created.'));
			}
		} finally {
			isBackingUp = false;
		}
	};
</script>

<div class="px-5 py-4">
	<Form.Root>
		<Form.Group>
			<Form.Label>{t('Language')}</Form.Label>
			<Form.Description>
				{t('Choose the language used in the app.')}
			</Form.Description>
			<SelectLocale bind:value={app.settings.locale} />
		</Form.Group>
		<Form.Group>
			<Form.Label>{t('Launch at startup')}</Form.Label>
			<Form.Description>
				{t('Enable or disable launching the application automatically when your system starts.')}
			</Form.Description>
			<Checkbox label={t('Launch at startup')} bind:checked={app.settings.autostart} />
		</Form.Group>
		<Form.Group>
			<Form.Label>{t('Close to tray')}</Form.Label>
			<Form.Description>
				{t(
					'Keep the app running in the system tray when you close the window so match tracking and overlays stay active. Use Quit from the tray menu to fully exit.'
				)}
			</Form.Description>
			<Checkbox label={t('Close to tray')} bind:checked={app.settings.closeToTray} />
		</Form.Group>
		<Form.Group>
			<Form.Label>{t('Company of Heroes warnings.log')}</Form.Label>
			<Form.Description>
				{t(
					'Select the warnings.log file generated by Company of Heroes. The app needs this file to detect your games.'
				)}
			</Form.Description>
			<FileSelection
				name="pathToConfig"
				bind:value={app.settings.companyOfHeroesConfigPath}
				filters={[{ name: 'warnings.log', extensions: ['log'] }]}
			/>
		</Form.Group>
		<Form.Group>
			<Form.Label>{t('Company of Heroes installation folder')}</Form.Label>
			<Form.Description>
				{t('Select the root installation folder of Company of Heroes (contains RelicCOH.exe).')}
			</Form.Description>
			<FileSelection
				name="pathToInstallation"
				directory
				bind:value={app.settings.companyOfHeroesInstallationPath}
			/>
		</Form.Group>
		<H level="4">{t('Fair play')}</H>
		<Form.Group>
			<Form.Label>{t('Fair play checks')}</Form.Label>
			<Form.Description>
				{t(
					'During a match the app takes random screenshots of the Company of Heroes window and checks for known cheat processes. These are uploaded for review and later analysis.'
				)}
			</Form.Description>
			<Checkbox label={t('Enable fair play checks')} bind:checked={antiCheat.settings.enabled} />
		</Form.Group>
		<H level="4">{t('Import / Export')}</H>
		<Form.Group>
			<Form.Label>{t('Import configuration')}</Form.Label>
			<Form.Description>
				{t(
					'Import a configuration JSON file to restore your settings. The file is validated first and applied immediately; nothing changes when the file is invalid.'
				)}
			</Form.Description>
			<Button variant="secondary" type="button" class="w-fit" onclick={() => app.importSettings()}>
				<ImportIcon />
				{t('Import')}
			</Button>
		</Form.Group>
		<Form.Group>
			<Form.Label>{t('Export configuration')}</Form.Label>
			<Form.Description>
				{t(
					'Export your full configuration (including your account and feature settings) to a JSON file.'
				)}
			</Form.Description>
			<Button variant="secondary" type="button" class="w-fit" onclick={() => app.exportSettings()}>
				<ExportIcon />
				{t('Export')}
			</Button>
		</Form.Group>
		<H level="4">{t('Backups')}</H>
		<Form.Group>
			<Form.Label>{t('Automatic backups')}</Form.Label>
			<Form.Description>
				{t(
					"Your settings and account are automatically backed up to {dir}, outside the app's data folder. They survive updates, even when you choose to remove all app data.",
					{ dir: backupDir }
				)}
				{#if lastBackupAt}
					<br />{t('Last backup: {date}', {
						date: dayjs(lastBackupAt).format('DD MMM YYYY, HH:mm:ss')
					})}
				{/if}
			</Form.Description>
			<Button
				variant="secondary"
				type="button"
				class="w-fit"
				onclick={backupNow}
				loading={isBackingUp}
			>
				<ArchiveIcon />
				{t('Backup now')}
			</Button>
		</Form.Group>
	</Form.Root>
</div>
