<script lang="ts">
	import * as Form from '$lib/components/ui/form';
	import { Button } from '$lib/components/ui/button';
	import { FileSelection, Checkbox, SelectLocale } from '$lib/components/ui/input';
	import { app } from '$core/app/context';
	import { settings } from '$core/config/settings.svelte';
	import { antiCheat } from '$core/app/features/anti-cheat';
	import dayjs from '$lib/dayjs';
	import ImportIcon from 'phosphor-svelte/lib/DownloadSimpleIcon';
	import ExportIcon from 'phosphor-svelte/lib/ExportIcon';
	import ArchiveIcon from 'phosphor-svelte/lib/ArchiveIcon';
	import { useI18n } from '$lib/i18n';
	import { openUrl } from '@tauri-apps/plugin-opener';

	const { t } = useI18n();
	const privacyUrl = 'https://coh1stats.com/privacy';

	let backupDir = $state('');
	let lastBackupAt = $state<Date | null>(settings.backup.lastBackupAt);
	let isBackingUp = $state(false);

	$effect(() => {
		settings.paths.backupDir().then((dir) => {
			backupDir = dir;
		});
	});

	const backupNow = async () => {
		isBackingUp = true;
		try {
			await settings.backup.backupNow('manual');
			lastBackupAt = settings.backup.lastBackupAt;
			if (settings.backup.lastError) {
				app.toast.error(t('Backup failed: {message}', { message: settings.backup.lastError }));
			} else {
				app.toast.success(t('Backup created.'));
			}
		} finally {
			isBackingUp = false;
		}
	};
</script>

<Form.Root>
	<Form.Group
		label={t('Language')}
		description={t('Choose the language used in the app.')}
	>
		<SelectLocale bind:value={app.settings.locale} />
	</Form.Group>
	<Form.Group
		label={t('Launch at startup')}
		description={t(
			'Enable or disable launching the application automatically when your system starts.'
		)}
	>
		<Checkbox label={t('Enabled')} bind:checked={app.settings.autostart} />
	</Form.Group>
	<Form.Group
		label={t('Close to tray')}
		description={t(
			'Keep the app running in the system tray when you close the window so match tracking and overlays stay active. Use Quit from the tray menu to fully exit.'
		)}
	>
		<Checkbox label={t('Enabled')} bind:checked={app.settings.closeToTray} />
	</Form.Group>
	<Form.Group
		label={t('Company of Heroes warnings.log')}
		description={t(
			'Select the warnings.log file generated by Company of Heroes. The app needs this file to detect your games.'
		)}
	>
		<FileSelection
			name="pathToConfig"
			bind:value={app.settings.companyOfHeroesConfigPath}
			filters={[{ name: 'warnings.log', extensions: ['log'] }]}
		/>
	</Form.Group>
	<Form.Group
		label={t('Company of Heroes installation folder')}
		description={t('Select the root installation folder of Company of Heroes (contains RelicCOH.exe).')}
	>
		<FileSelection
			name="pathToInstallation"
			directory
			bind:value={app.settings.companyOfHeroesInstallationPath}
		/>
	</Form.Group>
	<Form.Group label={t('Fair play')} />
	<Form.Group label={t('Fair play checks')}>
		{#snippet description()}
			{t(
				'During a match the app takes random screenshots of the Company of Heroes window and checks for known cheat processes. These are uploaded for review and later analysis.'
			)}
			<Button
				variant="link"
				class="h-auto px-0"
				type="button"
				onclick={() => openUrl(privacyUrl)}
			>
				{t('Privacy policy')}
			</Button>
		{/snippet}
		<Checkbox label={t('Enabled')} bind:checked={antiCheat.settings.enabled} />
	</Form.Group>
	<Form.Group
		label={t('All-chat announce')}
		description={t(
			'At the start of a match the app posts a short all-chat message so other players can see that fair play is on.'
		)}
	>
		<Checkbox
			label={t('Enabled')}
			bind:checked={antiCheat.settings.announceInChat}
			disabled={!antiCheat.settings.enabled}
			class="disabled:cursor-not-allowed"
		/>
	</Form.Group>
	<Form.Group label={t('Import / Export')} />
	<Form.Group
		label={t('Import configuration')}
		description={t(
			'Import a configuration JSON file to restore your settings. The file is validated first and applied immediately; nothing changes when the file is invalid.'
		)}
	>
		{#snippet footer()}
			<Button variant="secondary" type="button" class="w-fit" onclick={() => app.importSettings()}>
				<ImportIcon size={16} />
				{t('Import')}
			</Button>
		{/snippet}
	</Form.Group>
	<Form.Group
		label={t('Export configuration')}
		description={t(
			'Export your full configuration (including your account and feature settings) to a JSON file.'
		)}
	>
		{#snippet footer()}
			<Button variant="secondary" type="button" class="w-fit" onclick={() => app.exportSettings()}>
				<ExportIcon size={16} />
				{t('Export')}
			</Button>
		{/snippet}
	</Form.Group>
	<Form.Group label={t('Backups')} />
	<Form.Group label={t('Automatic backups')}>
		{#snippet description()}
			{t(
				"Your settings and account are automatically backed up to {dir}, outside the app's data folder. They survive updates, even when you choose to remove all app data.",
				{ dir: backupDir }
			)}
			{#if lastBackupAt}
				<br />{t('Last backup: {date}', {
					date: dayjs(lastBackupAt).format('DD MMM YYYY, HH:mm:ss')
				})}
			{/if}
		{/snippet}
		{#snippet footer()}
			<Button variant="secondary" type="button" class="w-fit" onclick={backupNow} loading={isBackingUp}>
				<ArchiveIcon size={16} />
				{t('Backup now')}
			</Button>
		{/snippet}
	</Form.Group>
</Form.Root>
