import type { CoHMaps } from "./types.js";

export const maps: CoHMaps[] = [
    '2p_angoville farms',
    '2p_beach_assault',
    '2p_beaux lowlands',
    '2p_bernieres-sur-mer',
    '2p_best',
    '2p_carpiquet',
    '2p_circle_wall',
    '2p_flooded_plains',
    '2p_langres',
    '2p_lyon',
    '2p_semois',
    '2p_st_mere_dumont',
    '2p_sturzdorf',
    '2p_verrieres_ridge',
    '2p_verrieres_ridge_no_bunkers',
    '2p_wrecked_train',
    '4p_achelous river',
    '4p_bedum',
    '4p_coastal_harbour',
    '4p_ecliptic fields',
    '4p_etavaux',
    '4p_linden',
    '4p_lorraine',
    '4p_lyon',
    '4p_mcgechaens war',
    '4p_point_du_hoc',
    '4p_rails and metal',
    '4p_st hilaire',
    '4p_vire river valley',
    '4p_wolfheze',
    '6p_close_river_combat',
    '6p_drekplaats',
    '6p_hedgerow_siege',
    '6p_hill 331',
    '6p_montherme',
    '6p_refinery',
    '6p_seine_river_docks',
    '6p_villers_bocage',
    '8p_best',
    '8p_king_of_the_hill',
    '8p_montargis region',
    '8p_route_n13',
    '8p_steel_pact',
    '6p_red_ball_express'
]