services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fknoobscoh-pocketbase
    ports:
      - '${PB_PORT:-8090}:${PB_PORT:-8090}'
    volumes:
      - pocketbase_data:/pb_data
    environment:
      - PB_PORT=${PB_PORT:-8090}
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}
      - SMURF_SERVICE_TOKEN=${SMURF_SERVICE_TOKEN}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - REPLAY_PROXY_SECRET=${REPLAY_PROXY_SECRET}
    env_file:
      - path: ./.env
        required: false
    restart: unless-stopped
volumes:
  pocketbase_data:
